### ISSUE TITLE
Development tokens for SDK

### ISSUE THREAD

**Issue by BlackthornProd** [GetStream/stream-chat-unity#12]
Hi,

It would be great to add development tokens into the Stream SDK.

**Comment by sierpinskid** [comment]
Hi, 
thanks for your contribution ;) I'll add the dev tokens generation very soon.

**Comment by sierpinskid** [comment]
For now, you can use the: [online token generator](https://getstream.io/chat/docs/unity/token_generator/?language=unity&q=token%20generator)

You can create new chat users in your Accont's Dasboard -> Explorer. Once you obtain the user id you can go to the online generator and combined with your API secret you can create valid auth tokens to login.

**Comment by sierpinskid** [comment]
Developer tokens are now included in the SDK, check out [the documentation](https://getstream.io/chat/docs/unity/tokens_and_authentication/?language=unity#developer-tokens) for code samples.

Please note that in order for developer tokens to work you need to enable "Disable Auth Checks" in your App's Dashboard.
