### ISSUE TITLE
Support for user data available without additional requesting inside of client class

### ISSUE THREAD

**Issue by zbigniewcebula** [GetStream/stream-chat-unity#21]
It would be nice to have some access to user data through already logged client.
When accesing with auth data, we have specific user bound to this auth, but we need to make additional request for user data by `QueryUsersRequest` to fetch some more from the database.
It would be nice at least to have that done by this initial `StreamChatClient.CreateDefaultClient` and stored inside of `IStreamChatClient` in some form of property.

Method that refreshes this property by just sending the request with current user id, would be cool too.

**Comment by sierpinskid** [comment]
Hi, thank you for your contribution! 

The local user data is being returned from the API when the connection is established. I'll expose this object as a property of `IStreamChatClient`. It's a small change so I should be able to add it tomorrow.

**Comment by sierpinskid** [comment]
The locally logged user object is now being returned via `IStreamChatClient.Connected` event.

You can update the local user state and assign any custom data with this snippet:
```
var response = await Client.UserApi.UpdateUserPartialAsync(new UpdateUserPartialRequest
{
	Users = new List<UpdateUserPartialRequestEntry>
	{
		new UpdateUserPartialRequestEntry
		{
			Id = _localUser.Id, //Replace with your local user ID
			Set = new Dictionary<string, object>()
			{
				{ "my_custom_field", 15 }
			},
		}
	}
});
```
Please note that this SDK is LLC (low-level client) and does manage the state. It provides an abstraction layer over Rest API and maintains a WebSockets connection. Once connected you will always receive the most recent state of the local user but when running any additional updates you must apply them to your local copy of the OwnUser as well.
