### ISSUE TITLE
No button to add channel in demo scene?

### ISSUE THREAD

**Issue by tomkail** [GetStream/stream-chat-unity#6]
Currently the demo scene doesn't allow sending messages without tinkering, because there's no default channel. Would suggest adding a button to create a new channel?

**Comment by sierpinskid** [comment]
Nice catch, thanks! Usually what users do is go to the [Stream App Dashboard](https://dashboard.getstream.io/) create the first user which is needed for the auth credentials and create a channel as well. 

But I'll definitely add it to the sample project.

**Comment by sierpinskid** [comment]
@tomkail I've added the create new channel button. Thanks for your contribution😃 

Here it is in action 💥:
 ![](https://github.com/GetStream/stream-chat-unity/blob/develop/ReadmeAssets/Other/NewChannelButtonPreview.gif)

**Comment by sierpinskid** [comment]
@tomkail I've added the create new channel button. Thanks for your contribution😃 

Here it is in action 💥:
 ![](https://raw.githubusercontent.com/GetStream/stream-chat-unity/develop/ReadmeAssets/Other/NewChannelButtonPreview.gif)
