### ISSUE TITLE
Addition/Removal overload that takes user ids

### ISSUE THREAD

**Issue by zbigniewcebula** [GetStream/stream-chat-unity#74]
Very useful overload for Adding/Removing Members of the channel would be nice, I don't like the idea to fetch channel member object only for removing it from the channel.
The permission should be also made bit more readable, because I do not see the **RemoveOwnChannelMembership** in **Available Permissions** list.

For example: current user wants to leave the channel... I have need to code too many steps to do that, but I could (like in JS):
`channel.removeMembers(['user-id']);`

**Comment by sierpinskid** [comment]
Hi,
Thank you for your contribution!

1. Adding the overloads
Sure I’ll throw them in :) 

2. Permission name
Thanks for spotting this! Permission names have a simplified friendly name in our Dashboard but the keys mentioned in the docs are still used when you want to manipulate the permissions via our API. We’ll look into it and fix the naming mismatch soon.

**Comment by sierpinskid** [comment]
Hi,
10 new overloads have been added to the `StreamChannel` class:
```
AddMembersAsync(IEnumerable<IStreamUser> users);
AddMembersAsync(params IStreamUser[] users);

AddMembersAsync(IEnumerable<string> userIds);
AddMembersAsync(params string[] users);

RemoveMembersAsync(IEnumerable<IStreamChannelMember> members);
RemoveMembersAsync(params IStreamChannelMember[] members);

RemoveMembersAsync(IEnumerable<IStreamUser> members);
RemoveMembersAsync(params IStreamUser[] members);

RemoveMembersAsync(IEnumerable<string> userIds);
RemoveMembersAsync(params string[] userIds);
```

You can add memebers by `IStreamUser` references or directly by their string ID.

```
// By IStreamUser reference
await channel.AddMembersAsync(users);

// By IStreamUser reference
await channel.AddMembersAsync(user1, user2, user3);

// By string ID
await channel.AddMembersAsync(userIds);

// By string ID
await channel.AddMembersAsync("user-id-1", "user-id-2");
```

You can remove members by `IStreamChannelMember` or `IStreamUser` reference, or directly by their string ID.
```
// Remove local user from a channel by user ID
var localUser = Client.LocalUserData.User;
await channel.RemoveMembersAsync(localUser.Id);

// Remove multiple users by their ID
await channel.RemoveMembersAsync("some-user-id-1", "some-user-id-2");

// Remove multiple users by their ID
await channel.RemoveMembersAsync(userIds);

// Remove by passing collection of IStreamChannelMember
await channel.RemoveMembersAsync(members);

// Remove by passing comma-separated IStreamChannelMember
await channel.RemoveMembersAsync(member1, member2, member3);

// Remove by passing collection of IStreamUser
await channel.RemoveMembersAsync(users);

// Remove by passing comma-separated IStreamUser
await channel.RemoveMembersAsync(user1, user2, user3);
```
