### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by tomkail** [GetStream/stream-chat-unity#9]
We've found that on WebGL, Stream doesn't seem to connect to websockets. The only log it gives is "Stream Chat: Attempt to connect". Is WebGL support on the roadmap?

**Comment by sierpinskid** [comment]
Sorry, you had a bad experience, I'll debug it asap and let you know. 

We aim to support all platforms supported by Unity.

**Comment by tomkail** [comment]
Np! I assumed it wasn’t supported, most chat SDKs don’t! When fixed you
should advertise that it supports WebGL, it’s something of a USP! :D
Ta!
